MobilePaywall.AndroidHttpService/Controllers/LiveController.cs
using MobilePaywall.AndroidHttpService.Models;
using MobilePaywall.Data;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using MobilePaywall.AndroidHttpService.Hubs;
using MobilePaywall.AndroidHttpService.Models.Input;
using MobilePaywall.AndroidHttpService.Database;

namespace MobilePaywall.AndroidHttpService.Controllers
{
  public partial class LiveController : Controller
  {

    public ActionResult Index()
    {
      LiveIndexModel model = new LiveIndexModel();
      return View(model);
    }

    public ActionResult CreateDistribution(string id)
    {
      int _gid = -1;
      if (!Int32.TryParse(id, out _gid))
        return this.Content("Could not parse id");

      AndroidDistributionGroup group = AndroidDistributionGroup.CreateManager().Load(_gid);
      if (group == null)
        return this.Content("Group is null");

      CreateDistributionModel model = new CreateDistributionModel();
      model.Group = group;
      return View(model);
    }

    public ActionResult CreateDistributionGroup()
    {
      return View();
    }

    public ActionResult AllDistribution(string id)
    {
      LiveDistributionModel model = new LiveDistributionModel();

      Data.AndroidDistributionGroup adg = Data.AndroidDistributionGroup.CreateManager().Load(int.Parse(id));
      List<Data.AndroidDistribution> androidDist= Data.AndroidDistribution.CreateManager().Load(adg);
      
      model.AndroidDistributions = androidDist;
      model.AndroidGroup = adg;
      return View(model);
    }

    public FileResult DistributionLogo(string id)
    {
      int _id = -1;
      if (!Int32.TryParse(id, out _id))
        return null;

      AndroidDistribution dis = AndroidDistribution.CreateManager().Load(_id);
      if (dis == null)
        return null;

      AndroidDistributionLogo logo = AndroidDistributionLogo.CreateManager().Load(dis);
      if (logo == null)
        return null;

      return new FileContentResult(logo.Data, "image/jpeg");
    }

    public ActionResult Distribution(string id)
    {
      Data.AndroidDistribution model = AndroidDistribution.CreateManager().Load(int.Parse(id));
      if (model == null)
        return this.Json(new { status= false, message = "Could not parse AndroidDistribution ID"});
      return View(model);
    }

    public ActionResult DistributionGroup() {
      DistributionGroupModel model = new DistributionGroupModel();
      model.DistributionGroups = AndroidDistributionGroup.CreateManager().Load();

      if (model == null)
        return this.Content("AndroidDistributionGroup is null");
      return View(model); 
    }

    public ActionResult OneDistributionGroup(string id)
    {
      Data.AndroidDistributionGroup model = AndroidDistributionGroup.CreateManager().Load(int.Parse(id));
      if (model == null)
        return this.Content("AndroidDistributionGroup is null");
      return View("~/Views/Live/OneDistributionGroup.cshtml", model);
    }

    public ActionResult GetDevices(LoadInputData data)
    {
      DevicesEntryManager manager = new DevicesEntryManager(data);
      if(manager.Error)
        return this.Json(new { status = false, message = manager.ErrorMessage });
      return PartialView("~/Views/Live/Partials/_Devices.cshtml", manager.Result);
    }

    public ActionResult Device(string sid)
    {
      int androidSessionID = -1;
      if (!Int32.TryParse(sid, out androidSessionID))
        return this.Content("could not parse sid");

      AndroidClientSession session = AndroidClientSession.CreateManager().Load(androidSessionID);
      if (session == null)
        return this.Content("There is no session with this id");

      List<AndroidClientLog> logs = AndroidClientLog.CreateManager().Load(session);
      return View("~/Views/Live/Device.cshtml", new LiveDeviceModel(session, logs));
    }

    public ActionResult Send(string value, string token)
    {
      return this.FirebaseSend(value, token, null);
    }


  }
}

MobilePaywall.AndroidHttpService/Views/Live/AllDistribution.cshtml
@model LiveDistributionModel

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/bootstrap.js"></script>

<style>
  .image {width:auto; height:25px; background-position:center; background-size:contain; background-repeat:no-repeat;}
</style>

<input class="btn btn-info" id="bacButton" style="margin:20px;" value="Back" onclick="window.location.href = '/Live/DistributionGroup';" />
<input class="btn btn-success" id="createButton" style="margin:20px;" value="Create Distribution" onclick="window.location.href = '/Live/CreateDistribution/' + @Model.AndroidGroup.ID;" />
 
<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Logo</th>
      <th>Group Name</th>
      <th>Name</th>
      <th>Descrption</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    @foreach (var dg in @Model.AndroidDistributions)
    {
      <tr>
        <td>@dg.ID</td>
        <td>
          <div class="image" style="background-image:url(/Live/DistributionLogo?id=@dg.ID)"></div>
        </td>
        <td>@dg.AndroidDistributionGroup.Name</td>
        <td>@dg.Name</td>
        <td>@dg.Description</td>
        <td>
          <input class="btn btn-default" type="button" id="editDistribution" value="Edit Distribution" onclick="location.href='@Url.Action("Distribution", "Live", new { id = @dg.ID })'" />
             <input class="btn btn-default" type="button" id="deleteDistribution" value="Delete Distribution" onclick="location.href='@Url.Action("ApiDeleteDistribution", "Live", new { id = @dg.ID })'" />
        </td>
      </tr>
    }
  </tbody>
</table>
<script src="~/Scripts/bootstrap-confirmation.min.js"></script>

MobilePaywall.AndroidHttpService/Views/Live/CreateDistribution.cshtml
@model CreateDistributionModel

@{
  Layout = null;
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<input hidden class="text" id="distributionGroup" value="" />

<input class="btn btn-info" id="bacButton" style="margin:20px;" value="Back" onclick="window.location.href = '/Live/DistributionGroup';" />

<div style="width:50%">
  <div class="form-group">
    <label for="exampleInputName2">Name</label>
    <input type="text" class="form-control" id="distributionName" value="">
  </div>
   <div class="form-group">
    <label for="exampleInputName2">Description</label>
    <input type="text" class="form-control" id="distributionDescription" value="">
  </div>

  <input class="btn btn-default" type="button" id="createDistribution" value="Create Distribution" />
</div>

<script>

  $(document).ready(function () {
    createDistribution();
  });

  function createDistribution() {
    $('#createDistribution').click(function (e) {
      e.preventDefault(); 
   //   var groupID = $('#selectGroup').find(":selected").attr('val');
      var name = $('#distributionName').val();
      var description = $('#distributionDescription').val();

      $.ajax({
        url: "/Live/ApiCreateDistribution",
        type: "POST",
        data: {
          name: name,
          groupID: @Model.Group.ID,
          description: description
        },
        success: function (data) {
          console.log(data);
          window.location.href = "/Live/DistributionGroup";
        },
        error: function (err) {
          console.log(err);
        }
      });


    });
  }

</script>

MobilePaywall.AndroidHttpService/Views/Live/CreateDistributionGroup.cshtml
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.10.2.min.js"></script>

<input hidden class="text" id="distributionID" value="" />

<input class="btn btn-info" id="bacButton" style="margin:20px;" value="Back" onclick="window.location.href = '/Live/DistributionGroup';" />

<div style="width:50%;margin:10px;">
  <div class="form-group">
    <label for="exampleInputName2">Name</label>
    <input type="text" class="form-control" id="distributionGroupName" value="">
  </div>
  <div class="form-group">
    <label for="exampleInputName2">Description</label>
    <input type="text" class="form-control" id="distributionGroupDescription" value="">
  </div>

  <input class="btn btn-default" type="button" id="createDistributionGroup" value="Create Distribution Group" />
</div>

<script>

  $(document).ready(function () {
    createDistributionGroup();
  });

  function createDistributionGroup() {
    $('#createDistributionGroup').click(function (e) {
      e.preventDefault();
      var name = $('#distributionGroupName').val();
      var description = $('#distributionGroupDescription').val();

      $.ajax({
        url: "/Live/ApiCreateDistributionGroup",
        type: "POST",
        data: {
          name: name,
          description: description
        },
        success: function (data) {
          console.log(data);
          window.location.href = "/Live/DistributionGroup";
        },
        error: function (err) {
          console.log(err);
        }
      });


    });
  }

</script>

MobilePaywall.AndroidHttpService/Views/Live/Device.cshtml
@model LiveDeviceModel
@{
  Layout = "~/Views/Live/_Layout.cshtml";
}
<link href="https://fonts.googleapis.com/css?family=Sintony" rel="stylesheet">
<link href="~/content/live/device.css" rel="stylesheet" />

<div id="template" style="display:none;">
  <div class="log log_recent" id="[ID]">
    <div class="tag">[TAG]</div>
    <div class="text">[TEXT]</div>
    <div class="created">[CREATED]</div>
  </div>
</div>

<div id="device_informations">
  <div class="devInfo_box">
    <div class="devInfo_title">Application name</div>
    <div class="devInfo_value">@Model.Session.AndroidDistribution.Name</div>
  </div>
  <div class="devInfo_box">
    <div class="devInfo_title">Application description</div>
    <div class="devInfo_value">@Model.Session.AndroidDistribution.Description</div>
  </div>
  <div class="devInfo_box">
    <div class="devInfo_title">Country</div>
    <div class="devInfo_value">@Model.Session.Country.GlobalName</div>
  </div>
  <div class="devInfo_box">
    <div class="devInfo_title">Device manifacturer</div>
    <div class="devInfo_value">@Model.Session.Company</div>
  </div>
  <div class="devInfo_box">
    <div class="devInfo_title">Model</div>
    <div class="devInfo_value">@Model.Session.Model</div>
  </div>
  <div class="devInfo_box">
    <div class="devInfo_title">SDK</div>
    <div class="devInfo_value">@Model.Session.VersionSDK</div>
  </div>
  <div class="devInfo_box">
    <div class="devInfo_title">OS</div>
    <div class="devInfo_value">@Model.Session.OSVersion</div>
  </div>
  <div class="devInfo_box">
    <div class="devInfo_title">Product</div>
    <div class="devInfo_value">@Model.Session.Product</div>
  </div>
  <div class="devInfo_box">
    <div class="devInfo_title">Device</div>
    <div class="devInfo_value">@Model.Session.Device</div>
  </div>
  <div class="devInfo_box">
    <div class="devInfo_title">Created</div>
    <div class="devInfo_value">@Model.Session.Created.ToString()</div>
  </div>
  <div class="devInfo_box">
    <div class="devInfo_title">OL link</div>
    <div class="devInfo_value">
      <a href="http://ol.app.mobilepaywall.com/Database?aid=@Model.Session.ID" target="_blank">OL data</a>
    </div>
  </div>
</div>

<div id="content">
  @foreach (MobilePaywall.Data.AndroidClientLog log in Model.Logs)
{
  string klass = log.FromDevice ? "log_in" : "log_out";
  <div class="log @klass">
    <div class="tag">@log.Tag</div>
    <div class="text">@log.Text</div>
    <div class="created">@log.Created.ToString()</div>
  </div>
}
</div>
<div id="input">
  <input type="text" value="" id="textInput" />
</div>


<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.signalR-2.2.1.min.js"></script>
<script src="../signalr/hubs"></script>
<script type="text/javascript">

  var sessionID = @Model.Session.ID;

  $(document).ready(function () {
    var live = $.connection.liveDeviceHub;
    live.client.update = function (data)
    {
      if (data.sessionID != '@Model.Session.ID')
        return;
      
      var html = $('#template').html();
      var id = ID('ne');
      html = html.replace('[ID]', id);
      $('#content').prepend(html);
      $('#' + id).find('.tag').html(data.tag);
      $('#' + id).find('.text').html(data.text);
      $('#' + id).find('.created').html(data.created);
      $('#' + id).addClass(data.fromDevice ? 'log_in' : 'log_out');
      setTimeout(function(){ $('#' + id).removeClass('log_recent'); }, 5000);

      //html = html.replace('[ID]', id);
      //html = html.replace("[TAG]", data.tag);
      //html = html.replace("[TEXT]", data.text);
      //html = html.replace("[CREATED]", data.created);
      //html = html.replace("[IN_OUT]", data.fromDevice ? 'in' : 'out');
      //$('#content').prepend(html);
    }

    $.connection.hub.start().done(function () { });

    $('#textInput').focus();
    $('#textInput').on('keypress', function (e) {
      if (e.which !== 13)
        return;

      if (typeof $(this).attr('disabled') !== 'undefined')
        return;

      var elem = $(this);
      var value = $(this).val();
      elem.attr('disabled', 'disabled');
      
      $.ajax({
        url: '/live/FirebaseSend',
        data: { message : value, tokenID : '@Model.Session.TokenID', sessionID: sessionID },
        method: 'POST',
        success: function(response)
        {
          if (!response.status)
            alert('error wtih sending');

          elem.removeAttr('disabled');
          elem.val('');
          elem.focus();
        }
      });
    });

  });

  function ID (prefix) {
    if (typeof prefix == undefined) prefix = ""; else prefix += "_";
    var text = "";
    var possible = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
    for (var i = 0; i < 15; i++) text += possible.charAt(Math.floor(Math.random() * possible.length));
    return prefix + text;
  }

</script>

MobilePaywall.AndroidHttpService/Views/Live/Distribution.cshtml
@model MobilePaywall.Data.AndroidDistribution
@{
  Layout = null;
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.10.2.min.js"></script>

<input hidden class="text" id="distributionGroupID" value="@Model.AndroidDistributionGroup.ID" />
<input class="btn btn-info" id="bacButton" style="margin:20px;" value="Back" onclick="window.history.back();" />

<div style="width:50%">
  <div class="form-group">

    <form action="/Live/ApiUpdateLogo" method="post" enctype="multipart/form-data">
      <input class="btn btn-default" type="file" name="file" />
      <input hidden id="distributionID" name="distributionID" value="@Model.ID"/>
      <input type="submit" value="Update Logo" class="btn btn-default" style="margin-top:25px;">
    </form>
  </div>
  <div class="form-group">
    <label for="exampleInputName2">Name</label>
    <input type="text" class="form-control" id="distributionName" value="@Model.Name">
  </div>
  <div class="form-group">
    <label for="exampleInputName2">Group ID</label>
    <input type="text" class="form-control" id="groupID" value="@Model.AndroidDistributionGroup.ID">
  </div>
  <div class="form-group">
    <label for="exampleInputName2">Description</label>
    <input type="text" class="form-control" id="distributionDescription" value="@Model.Description">
  </div>

  <input class="btn btn-default" type="button" id="updateDistribution" value="Update Distribution" />
</div>

<script>

  $(document).ready(function () {
    updateDistribution();
  });

  function updateDistribution() {
    $('#updateDistribution').click(function (e) {
      e.preventDefault();
      var groupID = $('#distributionGroupID').val();
      var id = $('#distributionID').val();
      var name = $('#distributionName').val();
      var description = $('#distributionDescription').val();

      $.ajax({
        url: "/Live/ApiUpdateDistribution",
        type: "POST",
        data: {
          id: id,
          name: name,
          description: description
        },
        success: function (data) {
          console.log(data);
          window.location.href = "/Live/AllDistribution/" + groupID;
        },
        error: function (err) {
          console.log(err);
        }
      });
    });
  }

</script>

MobilePaywall.AndroidHttpService/Views/Live/DistributionGroup.cshtml
@model DistributionGroupModel
  
<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
  
<input class="btn btn-info" id="bacButton" style="margin:20px;" value="Back" onclick="window.location.href = '/Live';" />
<input class="btn btn-success" id="bacButton" style="margin:20px;" value="Create Distribution Group" onclick="window.location.href = '/Live/CreateDistributionGroup'" />
<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Descrption</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    @foreach (var dg in @Model.DistributionGroups)
    {
      <tr>
        <td>@dg.ID</td>
        <td>@dg.Name</td>
        <td>@dg.Description</td>
        <td>
        <input class="btn btn-default" type="button" id="editDistributionGroup" value="Edit Distribution Group" onclick="location.href='@Url.Action("OneDistributionGroup", "Live", new { id = @dg.ID })'"/>
        <input class="btn btn-default" type="button" id="viewAllDistributionGroup" value="View All Distribution" onclick="location.href='@Url.Action("AllDistribution", "Live", new { id= @dg.ID})'" />
        <input class="btn btn-default" type="button" id="deleteDistributionGroup" value="Delete Distribution Group" onclick="location.href='@Url.Action("ApiDeleteDistributionGroup", "Live", new { id = @dg.ID })'" />
        </td>
      </tr>
    }
  </tbody>
</table>

<script>

</script>

MobilePaywall.AndroidHttpService/Views/Live/Index.cshtml
@model LiveIndexModel
@{
  Layout = "~/Views/Live/_Layout.cshtml";

  DateTime yesterday = DateTime.Now.AddDays(-1);
  DateTime tomorrow = DateTime.Now.AddDays(1);
  DateTime from = new DateTime(yesterday.Year, yesterday.Month, yesterday.Day, 0, 0, 0);
  DateTime to = new DateTime(tomorrow.Year, tomorrow.Month, tomorrow.Day, 7, 0, 0);
}
<link href="~/content/live/devices_list.css" rel="stylesheet" />
<link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
<script src="~/scripts/live/LiveDevices.js"></script>
<script src="~/Scripts/jquery.signalR-2.2.1.js"></script>
<script src="signalr/hubs"></script>

<div id="configuration">

  <table>
    <tr>
      <td>Top</td>
      <td>Country</td>
      <td>Application</td>
      <td>From</td>
      <td>To</td>
      <td></td>
    </tr>
    <tr>
      <td> <input type="number" class="input" id="input_top" value="50" /> </td>
      <td> <input type="text" class="input" id="input_country" /> </td>
      <td>
        <select class="input" id="input_application">
          <option value="-1"></option>
          @foreach (MobilePaywall.Data.AndroidDistribution app in Model.Distributions)
          {
            <option value="@app.ID">@app.Name</option>
          }
        </select> 
      </td>
      <td> <input type="text" class="input" id="input_from" value="@from"/> </td>
      <td> <input type="text" class="input" id="input_to" value="@to" /> </td>
      <td> <button id="btnSubmit" class="btns">Submit</button> </td>
      <td> <input type="button" class="btns" value="Distribution Groups" onclick="location.href='@Url.Action("DistributionGroup","Live")'" /> </td>
     
    </tr>
  </table>
</div>

<div id="data_loading"> Loading... </div>
<div id="data">

</div>

<script>
  var _manager = null;
  $(document).ready(function () {
    _manager = new LiveDevices();
    _manager.load();
  });
</script>

MobilePaywall.AndroidHttpService/Views/Live/OneDistributionGroup.cshtml
@model MobilePaywall.Data.AndroidDistributionGroup
@{
  Layout = null;
}

<link href="~/Content/bootstrap.min.css" rel="stylesheet" />
<script src="~/Scripts/jquery-1.10.2.min.js"></script>

<input hidden class="text" id="distributionID" value="@Model.ID"/>

<input class="btn btn-info" id="bacButton" style="margin:20px;" value="Back" onclick="window.location.href = '/Live/DistributionGroup';" />

<div style="width:50%">
  <div class="form-group">
    <label for="exampleInputName2">Name</label>
    <input type="text" class="form-control" id="distributionGroupName" value="@Model.Name">
  </div>
  <div class="form-group">
    <label for="exampleInputName2">Description</label>
    <input type="text" class="form-control" id="distributionGroupDescription" value="@Model.Description">
  </div>

  <input class="btn btn-default" type="button" id="updateDistributionGroup" value="Update Distribution Group" />
</div>

<script>

  $(document).ready(function () {
    updateDistributionGroup();
  });

  function updateDistributionGroup() {
    $('#updateDistributionGroup').click(function (e) {
      e.preventDefault();
      var id = $('#distributionID').val();
      var name = $('#distributionGroupName').val();
      var description = $('#distributionGroupDescription').val();

      $.ajax({
        url: "/Live/ApiUpdateDistributionGroup",
        type: "POST",
        data: {
          id: id,
          name: name,
          description: description
        },
        success: function (data) {
          console.log(data);
          window.location.reload();
        },
        error: function (err) {
          console.log(err);
        }
      });


    });
  }

</script>

MobilePaywall.AndroidHttpService/Views/Live/_Layout.cshtml
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <title>Android live</title>
  <script src="~/Scripts/_jq.js"></script>
</head>
<body>

  @RenderBody()

</body>
</html>